# Generated by Django 4.1.3 on 2023-02-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='player',
        ),
    ]
