# Generated by Django 4.1.3 on 2023-02-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_player_managed_by_alter_player_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='managed_by',
            new_name='manager',
        ),
    ]
