# Generated by Django 4.1.3 on 2023-02-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_managed_by_player_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='manager',
            new_name='managed_by',
        ),
    ]
