# Generated by Django 4.1.3 on 2023-02-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_remove_manager_email_remove_manager_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager_id',
        ),
    ]
