# Generated by Django 4.1.3 on 2023-02-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_rename_user_manager_manager_alter_player_managed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='referee_id',
        ),
    ]
