# Generated by Django 4.1.3 on 2023-02-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0010_rename_user_referee_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
    ]
