# Generated by Django 4.1.3 on 2023-02-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_referee_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='managed_by',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='club.manager'),
        ),
    ]
