# Generated by Django 4.1.3 on 2023-02-18 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0014_alter_manager_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coach',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='club.manager'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referee',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
